WebGame/Models/Participant.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebGame.Models
{
    public class Participant
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
    }
}

WebGame/Models/Room.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebGame.Models
{
    public class Room
    {
        public Guid Id { get; set; }
        public string  Name { get; set; }
        public bool IsFull { get; set; }
        public List<Participant> Participants { get; set; }
        
    }
}

WebGame/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace WebGame.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebGame/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;
using WebGame.Models;

namespace WebGame.Pages
{
    public class IndexModel : PageModel
    {
        private const string ROOMCACHEKEY = "RoomCacheKey";
        private readonly ILogger<IndexModel> _logger;
        private readonly IMemoryCache _memoryCache;

        [BindProperty]
        public List<Room> Rooms { get; set; }

        public IndexModel(IMemoryCache memoryCache, ILogger<IndexModel> logger)
        {
            _memoryCache = memoryCache;
            _logger = logger;
        }

        public void OnGet()
        {
            Rooms = _memoryCache.Get<List<Room>>(ROOMCACHEKEY);
            if (Rooms == null)
            {
                Rooms = new List<Room>();
                SetRoomCache(Rooms);
            }
        }

        public IActionResult OnPostAddRoom(string roomName)
        {
            if (ModelState.IsValid)
            {
                this.Rooms = _memoryCache.Get<List<Room>>(ROOMCACHEKEY);

                this.Rooms.Add(new Room() { Id = Guid.NewGuid(), Name = roomName, IsFull = false, Participants = new List<Participant>() });;
                SetRoomCache(this.Rooms);
            }
            return Page();
        }

        public IActionResult OnPostJoinRoom(Guid roomId, string Name)
        {

            if (ModelState.IsValid)
            {
                // Get rooms
                this.Rooms = _memoryCache.Get<List<Room>>(ROOMCACHEKEY);
                var theRoom = this.Rooms.FirstOrDefault(r => r.Id == roomId);
                if (theRoom != null)
                {
                    if (theRoom.Participants.Count > 1) return Page(); // limit to 2 partisipants
                    var participantId = Guid.NewGuid();
                    if (theRoom.Participants.Count == 0)
                    {
                        Name = "FirstPlayer";
                    }
                    else
                    {
                        Name = "SecondPlayer";
                        theRoom.IsFull = true;
                    }
                    theRoom.Participants.Add(new Participant() { Id = participantId, Name = Name });
                    SetRoomCache(this.Rooms);
                    return new RedirectToPageResult("Room", new { roomId, participantId });
                }
            }
            return Page();
        }
        public IActionResult OnPostJoinRoomByName(string roomName, string Name)
        {

            if (ModelState.IsValid)
            {
                // Get rooms
                this.Rooms = _memoryCache.Get<List<Room>>(ROOMCACHEKEY);
                var theRoom = this.Rooms.FirstOrDefault(r => r.Name == roomName);
                var roomId = theRoom.Id;
                if (theRoom != null)
                {
                    if (theRoom.Participants.Count > 1) return Page(); // limit to 2 partisipants
                    var participantId = Guid.NewGuid();
                    if (theRoom.Participants.Count == 0)
                    {
                        Name = "FirstPlayer";
                    }
                    else
                    {
                        Name = "SecondPlayer";
                        theRoom.IsFull = true;
                    }
                    theRoom.Participants.Add(new Participant() { Id = participantId, Name = Name });
                    SetRoomCache(this.Rooms);
                    return new RedirectToPageResult("Room", new { roomId, participantId });
                }
            }
            return Page();
        }

        private void SetRoomCache(List<Room> rooms)
        {
            var cacheExpirationOptions = new MemoryCacheEntryOptions()
            {
                AbsoluteExpiration = DateTime.Now.AddHours(5),
                Priority = CacheItemPriority.Normal,
                SlidingExpiration = TimeSpan.FromMinutes(10)
            };
            _memoryCache.Set(ROOMCACHEKEY, Rooms, cacheExpirationOptions);
        }
    }
}

WebGame/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace WebGame.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WebGame/Pages/Room.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;
using WebGame.Models;

namespace WebGame.Pages
{
    public class RoomModel : PageModel
    {
        private const string ROOMCACHEKEY = "RoomCacheKey";
        private readonly ILogger<RoomModel> _logger;
        private readonly IMemoryCache _memoryCache;

        [BindProperty]
        public Room Room { get; set; }

        [BindProperty]
        public Participant Participant { get; set; }



        public RoomModel(IMemoryCache memoryCache, ILogger<RoomModel> logger)
        {
            _memoryCache = memoryCache;
            _logger = logger;


        }
        public void OnGet(Guid roomId, Guid participantId)
        {
            var rooms = _memoryCache.Get<List<Room>>(ROOMCACHEKEY);
            if (rooms == null)
            {
                this.Room = new Room() { Participants = new List<Participant>() };
                return;
            }
            this.Room = rooms.FirstOrDefault(r => r.Id == roomId);
            if (this.Room != null)
            {
                this.Participant = this.Room.Participants.FirstOrDefault(p => p.Id == participantId);
            }
        }
    }
}

WebGame/Pages/Index.cshtml
@page
@model IndexModel

<div class="container">
    <div class="row">&nbsp;</div>
    <div class="row">
        <div class="col-12 d-flex justify-content-end">
            <form asp-page-handler="AddRoom" class="form-inline p-2 m-2" method="post">
                <div class="form-group">
                    <input type="text" name="roomname" class="form-control" placeholder="Room Name" />
                    <button type="submit" class="btn btn-secondary btn-lg">Add</button>
                </div>
            </form>
            <form asp-page-handler="JoinRoomByName" class="form-inline p-2 m-2" method="post">
                <div class="form-group">
                    <input type="text" name="roomName" class="form-control" placeholder="Room Name(Tag)" />
                    <button type="submit" class="btn btn-secondary btn-lg">Join</button>
                </div>
            </form>
        </div>
    </div>
    <div class="row">&nbsp;</div>
        @foreach (var room in Model.Rooms)
        {
            @if (!room.IsFull)
            {
                <div class="row row shadow-lg p-3 mb-5 bg-white rounded">
                    <div class="col">
                        <h1 style="margin:0">@room.Name</h1>
                    </div>
                    <div class="col">
                        @foreach (var participant in room.Participants)
                        {
                            <p>@participant.Name</p>
                        }
                    </div>
                    <div class="col">
                        <form asp-page-handler="JoinRoom" method="post">
                            <div class="d-flex justify-content-center">
                                <input type="hidden" name="roomid" value="@room.Id" />
                                <button type="submit" class="btn btn-secondary btn-lg ">Join</button>
                            </div>
                        </form>
                    </div>
                </div>
            }
        }

</div>

WebGame/Pages/Room.cshtml
@page
@model RoomModel
<div class="container">
    <div class="row">&nbsp;</div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header text-center">
                    <h1>@Model.Room.Name</h1>
                </div>
                <table class="table table-bordered text-center" id="table" style="visibility: hidden;">
                    <tbody>
                        @for (int i = 0; i < 3; i++)
                        {
                            <tr class="d-flex bd-highlight">
                                @for (int j = 0; j < 3; j++)
                                {
                                    <td class="flex-fill bd-highlight"><button class="btn btn-secondary" id="@(i*3+j)" disabled onclick="cl(this.id)">_</button></td>
                                }
                            </tr>
                        }
                    </tbody>
                </table>
                <div class="scroll card-body">
                    <div class="row">
                        <div class="col-6">
                            <ul id="messagesList"></ul>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row" id="typingIndicator" style="display: none">
                        <div class="col">
                            <p id="indicatorText" style="display: inline"></p>
                            <img src="../media/transgif.gif" alt="typing indicator" width="40" height="20" style="display: inline">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-2">Message</div>
                        <div class="col-6"><input onkeyup="indicateIsTyping()" class="col-12" type="text" id="messageInput" /></div>
                        <div class="col-4">
                            <input type="button" class="btn btn-secondary btn-lg" id="sendButton" value="Send Message" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




<input type="hidden" id="roomid" name="roomid" value="@Model.Room.Id" />
<input type="hidden" name="participantId" value="@Model.Participant.Id" />
<input type="hidden" id="ParticipantsCount" name="ParticipantsCount" value="@Model.Room.Participants.Count" />
<input type="hidden" id="participantName" name="participantName" value="@Model.Participant.Name" />
<input type="hidden" id="turn" name="turn" value="false" />

<script src="~/js/signalr/dist/browser/signalr.js"></script>

<script>
    "use strict";

    var connection = new signalR.HubConnectionBuilder().withUrl("/chatHub").build();

    if (document.getElementById("ParticipantsCount").value > 1) {
        document.getElementById("table").style.visibility = "visible";
    }
    
    function turn(name) {
        if (document.getElementById("participantName").value == name) {
            document.getElementById("turn").value = "false";
        } else {
            document.getElementById("turn").value = "true";
        }
        WhoWin();
        if (document.getElementById("turn").value == "true") {
            for (var i = 0; i < 9; i++) {
                if (document.getElementById(i).innerHTML == "_") {
                    document.getElementById(i).removeAttribute("disabled");
                }
            }
        } else {
            for (var i = 0; i < 9; i++) {
                document.getElementById(i).setAttribute("disabled", "disabled");
            }
        }
    }
    
    function WhoWin() {
        var m = 
            [
                [, , ],
                [, , ],
                [, , ]
            ];
        for(var i = 0; i < 3; i++) {
            for (var j = 0; j < 3; j++) {
                m[i][j] = document.getElementById(i * 3 + j).innerHTML;
                
            }
        }
        var userWin = "_";
        for (var i = 0; i < 3; i++)
        {
            if (m[i][0] != "_" && m[i][0] == m[i][1] && m[i][1] == m[i][2]) userWin = m[i][2];
            if (m[0][i] != "_" && m[0][i] == m[1][i] && m[1][i] == m[2][i]) userWin = m[0][i];
        }

        if (m[0][0] != "_" && m[0][0] == m[1][1] && m[1][1] == m[2][2]) userWin = m[2][2];
        if (m[0][2] != "_" && m[0][2] == m[1][1] && m[1][1] == m[2][0]) userWin = m[2][0];

        if (userWin != "_") {
            alert(userWin);
            window.location.href = '/';
        }
    }
    //Disable send button until connection is established
    document.getElementById("sendButton").disabled = true;
    
    connection.on("ReceiveMessage", function (user, message) {
        var msg = message.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
        var encodedMsg = user + " says " + msg;
        var li = document.createElement("li");
        li.textContent = encodedMsg;
        document.getElementById("messagesList").appendChild(li);
    });

    connection.on("Clicking", function (user, id)
    {
        if (user == "FirstPlayer") {
            document.getElementById(id).innerHTML = "x";
        } else {
            document.getElementById(id).innerHTML = "o";
        }
        turn(user);
    });

    connection.on("RoomUpdate", function (user) {
        document.getElementById("turn").value = "true";
        turn();
        document.getElementById("table").style.visibility = "visible";
    });


    function setIndicatorOff() {
        document.getElementById("typingIndicator").style.display = "none";
    }

    connection.on("Typing", function (user) {
        document.getElementById("indicatorText").innerHTML = user + " is typing";
        document.getElementById("typingIndicator").style.display = "block";
        setTimeout(setIndicatorOff, 2000);
    });

    connection.start().then(function () {
        document.getElementById("sendButton").disabled = false;
        var roomID = document.getElementById("roomid").value;
        var ParticipantsCount = document.getElementById("ParticipantsCount").value;
        
        if (ParticipantsCount > 1)
        {
            var user = document.getElementById("participantName").value;
            connection.invoke("UpdateRoom", roomID, user).catch(function (err) {
                return console.error(err.toString());
            });
        }
        connection.invoke("JoinRoom", roomID);
    }).catch(function (err) {
        return console.error(err.toString());
    });

    document.getElementById("sendButton").addEventListener("click", function (event) {
        var roomID = document.getElementById("roomid").value;
        var user = document.getElementById("participantName").value;
        var message = document.getElementById("messageInput").value;
        connection.invoke("SendMessage", roomID, user, message).catch(function (err) {
            return console.error(err.toString());
        });
        event.preventDefault();
    });

    var timerIsRunning = false;

    function setTimerRunningFalse() {
        timerIsRunning = false;
    }

    function indicateIsTyping() {
        if (timerIsRunning) {
            return;
        }
        timerIsRunning = true;
        var roomID = document.getElementById("roomid").value;
        var user = document.getElementById("participantName").value;
        connection.invoke("ParticipantTyping", roomID, user).catch(function (err) {
            return console.error(err.toString());
        });
        setTimeout(setTimerRunningFalse, 2000);
    }

    function cl(id) {
        var roomID = document.getElementById("roomid").value;
        var user = document.getElementById("participantName").value;
        connection.invoke("Change", roomID, user, id).catch(function (err) {
            return console.error(err.toString());
        });
    }
</script>

WebGame/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebGame</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">WebGame</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - 2021 - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>